### PR TITLE
Revert "Enabled WebKit prefill (WEBAPP-3210)"

### PR DESCRIPTION
**Pull request by bennyn**
Reverts wireapp/wire-webapp#631

### CODE REVIEW

**Comment by gregor** [comment]
avs

**Comment by lipis** [comment]
Maybe `color: #000;` instead of revert?

**Comment by bennycode** [comment]
@lipis: But then the background would still be yellow. 🦅

**Comment by gregor** [comment]
Background is the issue. White font color is correct. PR was intended to clear that.

**Comment by lipis** [comment]
opa.. yes.. my bad!

**Comment by bennycode** [comment]
There is another bug with... It prevents me from logging in:

capture

**Pull request merged**
