### PR TITLE
Removing redundant 'else'

### PR DESCRIPTION
**Pull request by lipis**
In all those cases the `else` is redundant plus the extra indentation..

http://stackoverflow.com/a/3261855/8418

Didn't find anything for CoffeeLint.. http://eslint.org/docs/rules/no-else-return

Search query used to find them all :)

```
return (.+)\n( +)else\n
```

In some cases I added an extra empty line.. in some not :) What do you guys think?

### CODE REVIEW

**Comment by bennycode** [comment]
I hope that there are tests to prove that the behaviour hasn't changed. ;)

**Comment by lipis** [comment]
Tests were nice in this case..

**Comment by bennycode** [comment]
I am afraid of merging this without tests. WDYT? I don't want to take the risk that it breaks something we don't know yet.

**Comment by lipis** [comment]
There are conflicts at the moment.. will take another swing at it :)

**Comment by bennycode** [comment]
@lipis What's the status on this one? Closing it?

**Comment by lipis** [comment]
Looks like the swing took longer.. let's close it until further notice :D

**Pull request closed without merging**
