### PR TITLE
feat: Enable video calls for guests and video group calls for personal users (WEBAPP-6909)

### PR DESCRIPTION
**Pull request by bennyn**

### CODE REVIEW

**Comment by atomrc** [comment]
Sweeettt ❤️

**Comment by bennycode** [comment]
@atomrc, more sweets are coming soon. 🍭🍭🍭

**Comment by atomrc** [comment]
Ohhh I like the sound of that 🍬

**Comment by atomrc** [comment]
... consider my curiosity piqued ;)

**Pull request merged**
