### PR TITLE
feat: Add a no-response bot

### PR DESCRIPTION
**Pull request by lipis**
For all the issues that are labeled `status: Need more info` and there is no response for 2 weeks.. it will mark the issues as closed. 

https://probot.github.io/apps/no-response/

### CODE REVIEW

**Comment by gregor** [comment]
Let's remove the sale bot at the same time then though

**Comment by lipis** [comment]
yes.. that was my thought! This one is less aggressive..

**Comment by gregor** [comment]
And let's wait with this change until after the long weekend just in case anything misbehaves and we need to deal with it.

**Comment by infotexture** [comment]
@lipis I updated the default response per our earlier discussion.

**Pull request merged**
