### PR TITLE
Make the fingerprint selectable

### PR DESCRIPTION
**Pull request by lipis**
Fixes #320

### CODE REVIEW

**Comment by herrmannplatz** [comment]
for the future we could introduce a generic class that forces text to be selectable

**Comment by herrmannplatz** [comment]
this way we could use it in several places

**Comment by lipis** [comment]
That's what I wanted in the beginning, but the way this was setup.. I think that made more sense.

Maybe instead of mixin it could be a normal class `.text-selection` and we could use it wherever we want in HTML.

**Comment by herrmannplatz** [comment]
Ah yeah sure. That might be the best option.

**Pull request merged**
