### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by herkyl**

### CODE REVIEW

**Comment by bennycode** [comment]
Hi @herkyl and thanks for your contribution!

Before we can accept your pull request you need to sign our contributor agreement:
https://github.com/wireapp/wire#contributing-to-the-code

All the best from Berlin,

Benny

**Comment by lipis** [comment]
I can't believe that our lint file had issues with indentation!! tsk tsk.. Thanks @herkyl

**Comment by bennycode** [comment]
@herkyl, please sign our CLA (https://github.com/wireapp/wire#contributing-to-the-code). Otherwise we need to close your PR by tomorrow. :cry:

**Comment by herkyl** [comment]
@bennyn done

**Comment by bennycode** [comment]
@herkyl thanks! But we just received an empty CLA from you. :cry:

**Pull request closed without merging**
