### PR TITLE
release 2017-12-04

### PR DESCRIPTION
**Pull request by gregor**

### CODE REVIEW

**Comment by lipis** [comment]
Is that about to go live?! 🔥

**Comment by gregor** [comment]
No, check the PR name. It give a hint on the release date 🙈

**Comment by lipis** [comment]
🙈

**Comment by gregor** [comment]
**?**

Any concerns with this release? It is tested and we intend to go ahead with the release as scheduled,

**Comment by lipis** [comment]
no no all good.. :) Just my blindness with the release date..

**Pull request merged**
