### PR TITLE
chore: Extract linter workflow

### PR DESCRIPTION
**Pull request by Yserz**

### CODE REVIEW

**Comment by lipis** [comment]
Just noticed that the `lint:spelling` script is not used anywhere in other scripts.. are we still using it?

**Comment by Yserz** [comment]
idk maybe something for another PR :)

**Comment by lipis** [comment]
Sure not for this one.. just mentioning it!

**Review by lipis — APPROVED** [review]

**Comment by ffflorian** [comment]
@lipis 

`lint:spelling` is not used because I found it too intrusive to run it every time since it's not *that* important. :slightly_smiling_face:

**Review by ffflorian — APPROVED** [review]

**Pull request merged**
