### PR TITLE
Drop YAML over JSON

### PR DESCRIPTION
**Pull request by lipis**
Just a test :P

### CODE REVIEW

**Comment by bennycode** [comment]
As this PR was just a test, can we close it?

**Comment by lipis** [comment]
Why test?! I thought we prefer JSON over YAML :)

**Comment by bennycode** [comment]
You wrote in your comment "Just a test :P"

**Comment by lipis** [comment]
Right :) Forgot about that comment... either case whatever we want :)

**Comment by bennycode** [comment]
@lipis, let's close this for now. If we bring up this discussion again we will go with `.js` rather than `.json`. 😁

**Comment by lipis** [comment]
Sure :)

**Pull request closed without merging**
