### PR TITLE
feat: Increase volume of audio files by 6dB

### PR DESCRIPTION
**Pull request by bennyn**
Resolves https://github.com/wireapp/wire-desktop/issues/1861

### CODE REVIEW

**Comment by johnstonesnow** [comment]
I am not too up to speed on how this place works, but does the fact the original thread has been closed, and the comments above, mean the audio alerts have been improved? If so I will install again and give it a try. Thanks

**Comment by bennycode** [comment]
@johnstonesnow Happy to tell you that louder audio files have been merged into our development branch. They will be available for public with our next webapp release which might land in production already by the end of this week. Will keep you posted. 🍀

**Comment by johnstonesnow** [comment]
Thanks. great to hear something has been done, especially after I had another email from support team saying nothing would be done about the alerts!! 
One question - web app - does that mean this change will only apply to the web version? I only use the installed version (on mac and windows)

**Comment by bennycode** [comment]
@johnstonesnow The change went live: https://medium.com/wire-news/wire-for-web-2018-11-30-b33cd69cf550 - Let us know if the volume is now to your liking. 🎶

**Comment by johnstonesnow** [comment]
Is this change applied across all versions or ONLY the web version of the app, as I don't use that. Thanks

**Comment by bennycode** [comment]
It's available on Web and Desktop.

**Comment by johnstonesnow** [comment]
Sehr gut, vielen dank!

**Comment by johnstonesnow** [comment]
Am I losing my marbles, or am I right in thinking the options have changed, with most options now only available in the paid version? It says calls, screensharing etc is only available in paid version, how long since that has been the case? I don't think it was like that when I started this thread or maybe I am losing the plot?!

**Comment by bennycode** [comment]
> It says calls, screensharing etc is only available in paid version, how long since that has been the case?

We haven't limited the existing feature set for [Wire Personal](https://wire.com/en/products/personal-secure-messenger/). Voice calling, video calling and screensharing is available in the free version and will work in 1:1 conversations. If you want to use these features in groups, you will need to upgrade to [Wire Pro](https://wire.com/en/products/pro-secure-team-collaboration/) but it has been always like that.

**Comment by johnstonesnow** [comment]
Ok thats good thanks. 
I can't find an update option in my installed version of Wire on MacOSX. Was going to re-download installer but it's forcing me through Apple App Store, which I don't want, I hate them tracking everything I do. Is there an updated mac installer I can find outside of the App Store, or is there a way to update my current version?
Thanks

**Comment by johnstonesnow** [comment]
Well I haven't updated mine but my friend installed the update version in Windows. We tested. Still completely inaudible. I read some reviews online of people in same situation as me, extremely keen to use it, but just can't due to lack of audible alerts. I am not a sound engineer but 6db sounds pretty small as an increase from practically silent. Maybe one day, if you decide to address this issue which clearly bothers a lot of people, maybe just install Skype, play with it and see how loud they are, then copy them. Wire could be (and no doubt wants to be) a replacement for Skype. The least you need to do, to make that possible, is provide the functionality Skype offers. I am grateful for your time, but this appears to have been a wasted exercise. I will keep looking for a chat client which I can use. Thanks.

**Pull request merged**
