### PR TITLE
docs: Do not install yarn via npm

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by bennycode** [comment]
What's bad on installing `yarn` with  `npm`?

**Comment by lipis** [comment]
it's not recommended by Yarn

**Comment by lipis** [comment]
You have a very old version of Yarn that suggests it I would guess :)

**Comment by bennycode** [comment]
@lipis: I am running on Yarn 1.1.0 which I installed from https://yarnpkg.com/en/docs/install#windows-tab

**Comment by lipis** [comment]
hmm.. so I'm wondering who is spitting that error actually? Husky? Yarn?

**Comment by bennycode** [comment]
Looks like husky wants yarn to be installed via npm.

**Pull request closed without merging**
