### PR TITLE
strings: Fix typo, 'anoyone'

### PR DESCRIPTION
**Pull request by wbnns**
## Type of change
This fixes a typo in which the word 'anyone' is incorrectly spelled as
'anoyone'.

### CODE REVIEW

**Comment by wbnns** [comment]
@herrmannplatz @gregor Hi there! Thanks for making this code available so people can make contributions. I just submitted this PR, however, apologies, I prefer not to authenticate services with my GitHub account (a requirement to sign the CLA). If it's not too much trouble, could one of you please cherry pick my commit (or make the fix yourself) to correct the spelling error?

Thanks in advance!

**Comment by lipis** [comment]
Maybe we still have somewhere our old way of signing the CLA, would you be interested in signing a PDF instead? (We don't want to "steal" the credit)

**Comment by wbnns** [comment]
@lipis Ok, thanks. Sure, happy to sign a PDF. 👍

**Comment by wbnns** [comment]
Just to confirm, no problem at all on my end (don't mind not getting any credit) if someone else who has already signed a CLA (or has merge access) wants to make this small typo fix so that it can get resolved for everyone.

**Comment by lipis** [comment]
I will close this one in favour of #593. Thank you @wbnns!

**Comment by wbnns** [comment]
@lipis Awesome, thank you sir! Happy Holidays! 👍

**Pull request closed without merging**
