### PR TITLE
Fixed wrong comment

### PR DESCRIPTION
**Pull request by cheeZery**

### CODE REVIEW

**Comment by bennycode** [comment]
Hi @cheeZery, thanks for your contribution (sharp eyes :wink:).

At the moment we are working on our contribution guideline. When we are done with this bureaucracy, we will merge your pull request.

Thanks a lot!

Benny

**Comment by cheeZery** [comment]
Hi Benny,

cool, thanks for your reply. I'm fairly new to Github and contributing to
open source software, so I wasn't sure what would be the right way to do
this (creating issue first, etc.), and just tried it this way :-)

You're very welcome and thanks for making Wireapp open source!

Carsten

**Comment by bennycode** [comment]
Hi Carsten,

Good news: We will have the legal framework ready by next week.
When it's there, I will give a shout here. :)

Best,
Benny

**Comment by bennycode** [comment]
@cheeZery: I am happy to tell you that we setup our legal framework for accepting pull requests. :smiley: 

Before we can accept your pull request you need to sign our contributor agreement:
https://github.com/wireapp/wire#contributing-to-the-code

All the best from Berlin,

Benny

**Comment by david-wire** [comment]
CLA received from @cheeZery and this is good for us to proceed.

**Comment by bennycode** [comment]
Thanks @david-wire & @cheeZery!

**Pull request merged**
