### PR TITLE
chore: Run scripts without git

### PR DESCRIPTION
**Pull request by ffflorian**
Follow-up to https://github.com/wireapp/wire-webapp/pull/7987.

This fixes https://github.com/wireapp/wire-webapp/issues/7985 (again).

### CODE REVIEW

**Comment by cgsadmin** [comment]
Hello ,
I got below errors when i installed and accessed web 

Access to XMLHttpRequest at 'https://staging-nginz-https.zinfra.io/activate/send' from origin 'http://xx.xx.xx.xx:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

image

**Comment by cgsadmin** [comment]
How to Run script without GIT ? is there any option ??

**Comment by cgsadmin** [comment]
its not yet done #8003  and still showing same issue once i downloaded updated package and installed 

And trying to run # yarn start and i opened web in browser and trying to get registration and it is same prompted issue was raised in #8003.

**Comment by ffflorian** [comment]
@cgsadmin this is not the right place to discuss errors in your setup.

**Pull request merged**
