### PR TITLE
remote video: double click to switch video between contain and cover view

### PR DESCRIPTION
**Pull request by d4l3k**
This is a pretty common feature in most video chat applications.

Screenshots: http://imgur.com/a/CEEUO

### CODE REVIEW

**Comment by bennycode** [comment]
Hi @d4l3k and thank you for your pull request! 

Unfortunately there is a linting error in `VideoCallingViewModel.coffe`. You can view the details here:
- https://travis-ci.org/wireapp/wire-webapp/builds/150209261

Before we can accept your pull request you also need to sign our contributor agreement:
https://github.com/wireapp/wire#contributing-to-the-code

Best from Berlin,
Benny

**Comment by d4l3k** [comment]
I signed the CLA and emailed it before submitting the PR.

**Comment by d4l3k** [comment]
Updated the PR to fix the linting errors. Haven't done much coffeescript before.

**Comment by d4l3k** [comment]
@bennyn On a side note, it'd be really great if you guys switched to something like https://cla-assistant.io/. Just makes it way easier to deal with.

**Comment by david-wire** [comment]
CLA received, all good to proceed.

**Comment by bennycode** [comment]
@d4l3k, we checked your pull request today with our design team and it's quite nice! We want to merge it but we need your help again to rebase your outdated branch. 

Please also set the default mode to `contain`:

``` coffeescript
@remote_video_object_fit = ko.observable 'contain'
```

Thank you for your neat contribution! :beers:

**Comment by d4l3k** [comment]
Done.

**Pull request merged**
